### ISSUE TITLE
Adaptive Sampling Experiment with MK1C 

### ISSUE THREAD

**Issue by husamia** [LooseLab/readfish#147]
ONT recently released a beta of the Adaptive Sampling on March 10th [https://community.nanoporetech.com/posts/beta-release-of-adaptive-s-7369](https://community.nanoporetech.com/posts/beta-release-of-adaptive-s-7369)

I think it's using the implementation in readfish? Anyway it was easy to setup. We did an enrichment experiment (2hrs). 

The installation instructions are clear and no errors encountered. I've drawn the enrichment setup below. The reference .fasta and the .bed design. Our target was 2K reads.

-chr22--------------|......................!..CYP2D6..!.......................|------------

|......................!..CYP2D6..!.......................|= ~24Kb region .fasta
                        !..CYP2D6..! = target .bed ~10Kb

We started the run and monitored the plots and it all looks great. We stopped the run after it looked like we have enough reads on target. ~2K 

![image](https://user-images.githubusercontent.com/13439952/116322168-78901a00-a789-11eb-8274-ddb73f52aa6a.png)
![image](https://user-images.githubusercontent.com/13439952/116322107-5c8c7880-a789-11eb-8050-a5cb80b6ff80.png)
![image](https://user-images.githubusercontent.com/13439952/116322120-63b38680-a789-11eb-8310-8329d2d825c8.png)
![image](https://user-images.githubusercontent.com/13439952/116322127-68783a80-a789-11eb-868f-cbfaf205d2d8.png)
![image](https://user-images.githubusercontent.com/13439952/116322065-4aaad580-a789-11eb-94f3-bba5be2dafb4.png)

Then, I looked at the alignments (bam_pass) and I was shocked that we havn't captured what we wanted. I matched the reads to whole genome and non match here, so it means minimap2 was making false positive alignments. 

![image](https://user-images.githubusercontent.com/13439952/116322397-053ad800-a78a-11eb-83ff-731eb7e7b535.png)

The read_until report:

555218 | unblock
8086 | no_decision
7 | unblock_hit_outside_bed

was the enrichment working? why wasn't there 2K reads on target that we expected?

**Comment by mattloose** [comment]
Hi,

OK - as you suggest ONT adaptive sampling uses the same approach to read until as readfish. However, the underlying mechanics of how it is implemented - in particular the downstream alignment algorithms etc are all by ONT and we can't help with the ONT software stack. So the short answer to your question is that you will need to go back to ONT customer support on this one.

I can make some general comments on things that look odd or unusual about the experiment or its design.

Firstly - I wouldn't use adaptive sampling to look for a single small region in a genome the size of the human genome. You have to sample and test every other read in your library to find the ones you are looking for and the proportion of reads in your input sample you are looking for is tiny. Almost all of your reads will be unblocked as they will fall outside your target. 

The read until report shows you this - everything has been rejected. You have 7 reads that are unblocked because they are outside your target region, but nothing on target. There is nothing in your read_until report to suggest sequencing any on target read.

Secondly you assume that minimap2 is making false positive alignments to your genome - but you are interpreting the alignment plot as showing reads that are on target - i.e are mapping to just the region of chr22 that you are interested in. This might be true - I don't know how the ONT alignment view is working here - but I'm not certain that it is showing alignment to your target region specifically. I also don't know if is distinguishing between sequenced and unblocked reads. So I would be running some kind of analysis on the read data to check where they are mapping and what I am seeing outside of the ONT tool chain to check.

Furthermore is there the possibility for your target that reads may also map from other regions of the genome at some lower level of mapping quality? Again - I don't know how the ONT code is implementing mapping filters etc etc. But is it possible that short fragments from the start of a read within your target region also map elsewhere in the genome (and vice-versa?). As an aside, I note that you are running on the Mk1C - I believe that in order to get this performant enough, ONT are using a faster base calling model - this model will most likely give you noisier reads - they will be sufficient for general placing but if you are in a region with similarity to other regions in the genome you will be increasing the chances of seeing off target reads miscalled as on target.

Finally your duty time plot looks very strange. At around 5 minutes, 12 minutes, 18 minutes and 32 minutes your occupancy goes up dramatically. This is what we would expect to see if adaptive sampling had been switched off for brief periods of time. This will - of course - affect your results as you will get long reads in your data that will map to random regions of the genome from those periods of time (if - as I suspect - adaptive sampling isn't working for those moments in time).

So - I'm sorry your experiment hasn't proceeded as you might expect - I think this is most likely a combination of many factors and will require you talking with ONT to resolve.

Whilst I have commented here to try and help as much as I can I am afraid that we cannot support ONT software on this repository so please direct any further comments and questions to ONT customer support directly unless using our readfish code.

Cheers

Matt
