### ISSUE TITLE
readfish 0.0.11a4 on MinION sequencing toml requires break_reads_after = 1.0 

### ISSUE THREAD

**Issue by rainwala** [LooseLab/readfish#234]
We seem to have found a situation that requires `break_reads_after = 1.0` rather than `break_reads_after = 0.4` in the sequencing toml file.

We have just run readfish version 0.0.11a4 from dev_staging on a MinION MK1B  with the following software versions:
MinKNOW 22.12.7
MinKNOW core 5.4.7
Guppy 6.4.6
Bream 7.4.8
Script Configuration 5.4.7

Our system and GPU is:
Ubuntu 18.04 LTS
NVIDIA GeForce RTX 2080

with script "sequencing_MIN114_DNA_e8_2_400T_readfish.toml" and the parameter: 
`break_reads_after = 0.4`

We get very poor quality scores, and slow unblocking, as shown here:
![image](https://user-images.githubusercontent.com/14825266/229481721-991db20f-9848-4237-9079-c8b1a59f7ada.png)
![image](https://user-images.githubusercontent.com/14825266/229481779-3141e5fc-c3f0-4922-bbf7-103e03259d4e.png)

When we change the break_reads_after parameter value to 1.0:
`break_reads_after = 1.0`

The quality scores get much better, and the unblock lengths settle down to ~500bp:
![image](https://user-images.githubusercontent.com/14825266/229482697-6ef6c601-91a4-48b2-ae1e-a7d51613b2fd.png)
![Screenshot_2023-03-31_17-10-43](https://user-images.githubusercontent.com/14825266/229482749-c7d4cabe-3af9-4523-9506-ec31eb3c3be3.png)

This makes for a run that seems like it will work, as opposed to the situation with `break_reads_after = 0.4`

I just wanted to flag this issue.

**Comment by samhorsfield96** [comment]
I have also just encountered the issue with low read quality using V14 chemistry (sequencing_MIN114_DNA_e8_2_400T.toml) using readfish 0.0.10dev2, however the unblock read lengths looked fine. Did the enrichment results look as expected using this fix?

**Comment by rainwala** [comment]
I'm about to test the enrichment over the next few days. Will post an update after that.

**Comment by rainwala** [comment]
OK, so with this new run even setting break_reads_after = 1.0 didn't fix the issue. We had poor quality and unblocked read lengths were well over 1kb... Maybe we need a new GPU...

**Comment by mattloose** [comment]
OK - whilst I would still advise one second for running at present, I am not convinced that the quality issue here is related to the break reads setting. The quality that @rainwala is showing above is lower than I would expect. As an example, here is a run we currently have on promethION which is running adaptive with break reads at 1 second using kit14:

![image](https://user-images.githubusercontent.com/8202484/233072886-318a08a5-240e-445a-9432-d6c08e2cdcc0.png)
 (This is the modal quality score).

You can see the unblock peak is fine - 
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/8202484/233073304-6abdaa9d-3689-4df4-809e-1ddd7736245e.png">
And the unblock read length N50 is around 900 bases.

We are unblocking a lot of the data here which is why you can't see any on target reads at all.

If I zoom in on the approrpriate lengths we see this: 
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/8202484/233073595-836f9320-ca53-40e4-9ea2-0d6984e3bfa3.png">

Having said all the above, I do note that I see some strange differences in the sequenced reads when measuring read quality. I've not noticed specifically that this impacts enrichment and I would actually look at the aligned data and not the quality scores as reported by minknow.

My conclusion with the observation of @rainwala is that this might be a more fundamental library quality issue. @samhorsfield96 can you provide any more information on what you have seen?

Also can you report minKNOW versions here too?

**Comment by mattloose** [comment]
Could you both check the accuracy of on target and off target reads after mapping to the reference and look at the quality that way?

**Comment by samhorsfield96** [comment]
Hi @mattloose sorry for not getting back sooner. Alignment looks fine using pass and fail reads - I haven't got formal measures of quality, however when looking at enrichment by abundance, values are as expected even using failed reads. I've noticed that the high volume of failed reads doesn't happen with every run either, and when running with the exact same setup and library I get different outcomes (sometimes many reads fail, sometimes the run looks normal). Not sure if this info helps your end, but it looks to me that using 'failed' reads doesn't actually impact alignment or calculation of enrichment.

**Comment by mattloose** [comment]
Closing as stale.
