### ISSUE TITLE
Unexpected readfish stats results with prom playback: Lower enrichment for target than control

### ISSUE THREAD

**Issue by DanteV19** [LooseLab/readfish#387]
Dear developer,

I have been having some unexpected results from Readfish with my own prom bulk file (5khz) for playback.

I tried to enrich for chr10 to test whether the Readfish adaptive sampling is performed well.
See below for the toml file I used.
![image](https://github.com/user-attachments/assets/da9297cf-8d5c-41ad-9c30-dc4d9a0c2c73)

However, the results from the `readfish stats` command showed less enrichment for ch10 for the _hum_test_ run (Median read lengths=835b, N50=1.68Kb) than the _control_ run (Median read lengths=1.13Kb, N50=2.53Kb) even though the right non-target reads do seem being unblocked.

For the complete `readfish stats` output see the file below.
[readfish_stats_21oct_prom_ch10_9q_own_bulk_2h.txt](https://github.com/user-attachments/files/17468724/readfish_stats_21oct_prom_ch10_9q_own_bulk_2h.txt)

It is my assumption that unblocking non-target reads during a sequencing run will lead to more time for more target reads to be fully sequenced. Consequently, I should have had a higher enrichment for ch10 in the "hum_test" run than the "control" run.

Am I right in my assumptions or is there an explanation for the `readfish stats` results?

Let me know if you need more information.

Thanks in advance

**Comment by Adoni5** [comment]
Hey @DanteV19 - you've fallen foul of using playback to test the experimental output of adaptive sampling, I should probably add this to the FAQ. There's an issue somewhere detailing this, but I can't find it so I'll provide a brief summary here.

When you perform playback, the bulk file is a complete record of the current sensed by each pore. This is then recreated, for the play back run. When you send an unblock for a period of current representing a read, that read is "unblocked". However there is no altering the current recorded in the bulk file, and so the current resumes, and a new read, is recorded, which is just a continuation of the "unblocked" read.

Therefore it is impossible to achieve enrichment when using playback, as in actuality you are just segmenting complete reads into unblocked chunks. In fact you might see some decrease compared to control, due to small gaps in between each chunk, which would be present in the complete read seen in the control section.

**Comment by Adoni5** [comment]
There is - it's not the easiest thing to use but i wrote it to test experimental setups -q https://github.com/LooseLab/Icarust

**Comment by DanteV19** [comment]
Thanks for your suggestion.
I will try to use Icarust to test the enrichment for my expression data and if I encounter any difficulties I would like to ask for help again.

**Comment by DanteV19** [comment]
Hi @Adoni5,
I have some questions about readfish stats that just occurred to me.

When performing readfish stats you can demultiplex the reads into *__proceed.fastq.gz_, *__stop_receiving.fastq.gz_ and *__unblock.fastq.gz_ in my case for control and hum_test.

Since I did playback sequencing, I do not know for certain if _hum_test_unblock.fastq.gz_ contains fully sequenced reads or only the segment of the read up until where it was "unblocked". Considering there is no altering the current recorded in the bulk file. I have noticed there were read lengths of over 1000 bases in _hum_test_unblock.fastq.gz_ and I am not sure if this is normal or because of playback or an error.

I intend to calculate the total number of the remaining bases of each "unblocked" read from _hum_test_ that would have been sequenced in  _control_ in order to estimate the time that I would have saved with adaptive sampling.

So, my questions are:

- Would it be possible to make this calculation with intersecting read IDs from the demultiplexed files from `readfish stats` (_control_stop_receiving.fastq.gz_ and _hum_test_unblock.fastq.gz_)? Why (not)? If not, is there another way to calculate the estimated saved time from remaining bases of "unblocked" reads from playback?
- After doing playback, does the *_unblock.fastq.gz file, demultplexed from `readfish stats`, only contain reads up until the rejecting signal or the fully sequenced read as recorded in the bulk file?


Thanks in advance
