### ISSUE TITLE
MinKNOW not installed

### ISSUE THREAD

**Issue by awjga** [LooseLab/readfish#63]
Hi,

I am using Ubuntu 20.04.
The latest version of MinKNOW and Guppy 3.4.5.

I am using my own bulk fast5 for simulation.
Guppy server running and MinKNOW is sequencing in the background.

But when I am trying to run
"readfish unblock-all --deviceMN29650 --experiment-name "Testing ReadFish Unblock All""

An output similar to MInKNOW not installed or MInKNOW not detected, and the software would stop.

I had tried using Ubuntu 18.04 but it results in the same error.

**Comment by mattloose** [comment]
Hi

Are you using Minknow 4.0? If so, we are in the process of updating our tools for Minknow 4.0 and hope to have an experimental branch by the end of the week.

The message that readfish can’t find Minknow is related to how we communicate with the software. 

Please check which Minknow version you have. 

Matt

**Comment by XPHenry** [comment]
I had the same problem, apparently, it's trying to point at python2.7, which is not installed by default with Minknow 4.0
Looking forward for an update

**Comment by mattloose** [comment]
So - to clarify - MinKNOW 4.0 uses a different underlying RPC - we are in final testing of our read until code for MinKNOW 4.0 but we obviously don't want to release it until we are certain that it is robust. I hope it will be either end of this week or beginning of next.

However - the code is giving the expected behaviour right now!

**Comment by awjga** [comment]
Thanks for the clarifications.
Yes I am currently using Minknow 4.0.

I will test it when you have released the updated version.

Thanks!
