### ISSUE TITLE
select_chr_21_22 did not work in readfish targets

### ISSUE THREAD

**Issue by HJTsai** [LooseLab/readfish#64]
Hi,

We test readfish unblock-all and it works.
However, select_chr_21_22 did not work in readfish targets.
![messageImage_1598244786470](https://user-images.githubusercontent.com/49969700/91029560-81947e80-e631-11ea-8e78-68ca7120e60d.jpg)

The version in our system:
Minknow-core-gridion 4.0.3
Ont-guppy-for-gridion 4.0.11

Should we run guppy_basecall_server (3.4.5) during readfish targets?
The basecall server (3.4.5) has been terminated, but the basecall server (4.0.X) has been connected.
If guppy_basecall_server (3.4.5) is required, How to resolve the connection setup?

basecall server (3.4.5)
![messageImage_1598247442408](https://user-images.githubusercontent.com/49969700/91030151-b30d4a00-e631-11ea-8a2f-092410d63576.jpg)

basecall server (4.0.X)
![messageImage_1598247410739](https://user-images.githubusercontent.com/49969700/91030409-c0c2cf80-e631-11ea-81e7-a6b0a95004bb.jpg)

The format of log file is different between ru_generators and readfish targets.
Is it right?

ru_generators
![messageImage_1598245031995](https://user-images.githubusercontent.com/49969700/91030537-e7810600-e631-11ea-8e1a-cdf5f2d9246e.jpg)

readfish targets
![messageImage_1598244997429](https://user-images.githubusercontent.com/49969700/91030570-f49df500-e631-11ea-9f5f-98f3f7acfa9e.jpg)

Sincerely,

Amber

**Comment by alexomics** [comment]
Hi Amber, 

The current in development version of readfish (v0.0.5a2) is built to work with minknow-core 4 and guppy 4. `ru_generators` is for minknow-core 3 and guppy 3. 

I noticed that the reference files provided to `readfish targets` and `ru_generators` are different. I'm not sure if this is intentional, but suggests that the TOML files are not the same between these runs. 

Finally in the summary output the number of reads in `chr21` and `chr22` are much lower than those on other chromosomes, suggesting that these are being selected for while the others are being unblocked.

What version of readfish are you using? How was it installed? What python version are you running under? Could you also provide a sample of the TOML file that you are using?

Alex

**Comment by HJTsai** [comment]
Hi Alex,

The version of readfish is 0.0.5a1 and Python is 3.6.12.
Readfish was installed via https://pypi.org/project/readfish/0.0.5a2/.
TOML file was attached.
![messageImage_1598327069536](https://user-images.githubusercontent.com/49969700/91130383-28ceef80-e6de-11ea-9097-e8726ffc8fbb.jpg)

Thanks.

Amber

**Comment by alexomics** [comment]
Could you provide some details about your computer’s specifications? What CPU, GPU, and memory it has? 

How are you running the guppy server in these tests? Are you running live base calling at the same time?

Have you changed the `break_reads_after_seconds` parameter in MinKNOW?

**Comment by HJTsai** [comment]
Hi Alex,

CPU : Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
GPU : GeForce GTX 1080 Ti (x2)
Memory : DIMM Synchronous 2133 MHz 16 GB(x4)

minknow-core 3 and guppy 3. (ru_generators)
Guppy server is running through below command
cd /data/read_until/guppy_3.4.5/bin
sudo ./guppy_basecall_server -p 1688 --log_path /data/guppy_server_log --config dna_r9.4.1_450bps_fast.cfg --device cuda:all

minknow-core 4 and guppy 4. (readfish)
The basecall server (3.4.5) has been terminated, but the basecall server (4.0.X) has been connected.

We had changed the parameter break_reads_after_seconds = 1.0 to break_reads_after_seconds = 0.4.

Amber

**Comment by HJTsai** [comment]
Hi Alex,

minknow-core 4 and guppy 4. (readfish)
Guppy server is running through below command (guppy 4.0.11)
cd /opt/ont/guppy/bin/
sudo ./guppy_basecall_server -p 1688 --log_path /data/guppy_server_log --config dna_r9.4.1_450bps_fast.cfg --device cuda:all

Could you provide the package lists of python 3.6.12 for readfish?
We want to make sure these packages are installed in our venv environment.

Amber

**Comment by HJTsai** [comment]
Hi Alex,

The results from the same fast5 bulk file are different between minknow-core 3 and guppy 3. (ru_generators) and minknow-core 4 and guppy 4. (readfish).
ru_generators max_chank=8
![max=8](https://user-images.githubusercontent.com/49969700/91696631-73e77780-eba2-11ea-91f9-18ffe2e6e10a.jpg)

ru_generators max_chank=64
![max=64](https://user-images.githubusercontent.com/49969700/91696651-79dd5880-eba2-11ea-838b-13d11d10fde6.jpg)

readfish target max_chank=8
![max=8_readfish](https://user-images.githubusercontent.com/49969700/91696664-7f3aa300-eba2-11ea-8f3b-ebaf378e8f12.jpg)

readfish target max_chank=64
![max=64_readfish](https://user-images.githubusercontent.com/49969700/91696674-83ff5700-eba2-11ea-9b22-53feffa61bef.jpg)

Do you have any suggestion for max_chunk setting?
Could you provide the result of select_chr21_22 that running by readfish target?

According to the pattern of read length histogram, whether most reads were exceed max_chunk?
![S__16916486](https://user-images.githubusercontent.com/49969700/91697679-19e7b180-eba4-11ea-9910-0bba33df24ea.jpg)

Hoping that this will not cause you too much trouble.

Amber

**Comment by 2387882242** [comment]
Hi Alex，

I'm having the similar problem with Amber. And I still have two puzzles:

a. My readfish summary also shows that the number of reads in chr21 and chr22 are lower than other chromosomes, but the median difference is not significant. Is the test result enough for me to do a real experiment or do I need to make further adjustments？

b. I installed Readfish via https://pypi.org/project/readfish/0.0.5a2/， but my readfish version is 0.0.5a1. Is it due to the Python version？Does it affect the results？

**Comment by Huanle** [comment]
Hi @HJTsai has this been sorted out?
