### ISSUE TITLE
Sudden RU stop during barcoding experiment

### ISSUE THREAD

**Issue by joanmarticarreras** [LooseLab/readfish#82]
Hi,

Yesterday I started my first target enrichment with RU/ReadFish on a real sequencing experiment (I used the following conda script to create the environment for the run):

```
name: readfish_env_4
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python==3.7
  - pip
  - pip:
    - readfish==0.0.5a2
    - git+https://github.com/nanoporetech/read_until_api

```

In this sequencing experiment I was willing to test the usefulness of RU on capturing a given viral pathogen from human DNA background by spiking different DNA samples with different titrated copy numbers of my pathogen of interest. Those samples were later barcoded with NBD and prep'd with LSK119 (as we discussed with @mattloose in another thread).

The beginning seemed very promising (all intervals of screening were between 0,3 - 0,5 s). After a couple of hours monitoring, I went home.

Unfortunately, the first thing I see today in the morning, is that **RU has stopped screening after 4h of the start of the run.** There is no error message in the log file (attached), just the last date/hour of activity corresponds to 4h after the run. Ofc, it has continued running for the whole night, therefore it is difficult now to assess how good was the enrichment due to RU.

Here what my .toml looks like:

```
[caller_settings]
config_name = "dna_r9.4.1_450bps_hac"
host = "127.0.0.1"
port = 5555

[conditions]
reference = "./NC_006273.2.mmi"

[conditions.0]
name = "HCMV"
control = false
min_chunks = 0
max_chunks = inf
targets = ["NC_006273.2"]
single_on = "stop_receiving"
multi_on = "stop_receiving"
single_off = "unblock"
multi_off = "unblock"
no_seq = "proceed"
no_map = "proceed"

```

If interested, I saved the bulk file of this experiment, please let me know by mail so I can provide a temporary link to it for you to assess what may have happened.

[20200930_RU_NC_006273.log](https://github.com/LooseLab/readfish/files/5310350/20200930_RU_NC_006273.log)

**Comment by mattloose** [comment]
HI,

Firstly - sorry to hear about this. Because of the way all of the software for read until works, plugging in to several different routes, it is difficult to catch all possible errors.

We have - rarely - had this type of problem and it is difficult to troubleshoot. 

The problems can include: 
1. MinKNOW stopping sending data.
2. ReadFish crashing (not the case here).
3. Communication with Guppy failing.

It is difficult to detect 1 and 3 in our code, but is something we are looking into doing in the future.

To troubleshoot what has happened here, you need to look in the MinKNOW and Guppy logs on your system and determine if there are any errors.

If you find any can you please share them here?

Unfortunately the bulkfile won't allow us to work out what has happened here.

It would also be helpful to know which version of guppy you are running. Other users have reported some guppy stability problems (this may well be apparent in the log files).

With respect to analysis to see if your run has worked, it should be possible to pull out all reads up to the time point that ReadUntil stopped and analyse them that way?

Final question. If ReadFish detected a problem with running read until, what would your preferred action be? We could place a notification in MinKNOW, an alert on the screen or potentially pause or stop the sequencing run. We are hesitant about how best to implement this and feedback would be appreciated!

Again - our apologies this hasn't worked as expected - unfortunately it is likely beyond our control but we would like to be able to resolve this for you.

**Comment by joanmarticarreras** [comment]
Hi,

Firstly, I checked some of the log files, and I got this on **guppy_basecall_server_log-2020-09-28_12-34-43.log** file:

```
2020-09-30 14:54:38.209243 [guppy/info] Client with id 3 has disconnected.                                                                                  
2020-09-30 14:54:40.047084 [guppy/info] client connection request. ["dna_r9.4.1_450bps_hac:::"]
2020-09-30 14:54:40.047170 [guppy/info] New client connected with id 5 (connection string = 'dna_r9.4.1_450bps_hac:::').                                       
2020-09-30 16:43:25.693062 [guppy/info] Client with id 5 has disconnected.
2020-10-01 09:45:45.414145 [guppy/info] Client with id 4 has disconnected.                                                                                                                             2020-10-01 09:45:45.451473 [guppy/info] client connection request. ["dna_r9.4.1_450bps_fast:>require_barcodes_both_ends=false>detect_mid_strand_barcodes=false>barcode_min_score_front=60>barcode_min_score_rear=60:EXP-NBD114:false:/home/luna.kuleuven.be/u0117540/READUNITL/NC_006273.2.fasta"]
```
I attach the different log files for further debugging:

- [bream-0.txt](https://github.com/LooseLab/readfish/files/5311625/bream-0.txt)

- [control_server_log-0.txt](https://github.com/LooseLab/readfish/files/5311626/control_server_log-0.txt)

- [guppy_basecall_server_log-2020-09-28_12-34-43.log](https://github.com/LooseLab/readfish/files/5311627/guppy_basecall_server_log-2020-09-28_12-34-43.log)

- [analyser_log-0.txt](https://github.com/LooseLab/readfish/files/5311628/analyser_log-0.txt)


Seems that the client disconnected? But the sequencing continued? Excuses, but this is a bit out of my ally and I am a bit confused of what happened exactly ... If you or any of your team could offer further clarification, I'd appreciate. Still have some flowcells I could use/burn.

Just FYI, I am running guppy 4.0.11+f1071ce.

If ReadUntil displayed an error during the run, I think it should be displayed both in the log file and in MinKNOW. Also, might not be bad a idea to send a notification by mail (very often we leave runs O/N). Regarding the run, maybe it should enter PAUSE. It might be that the error can be solved easy and fixed in a matter of minutes/hours.
