### ISSUE TITLE
Does the accumulating read cache work in 0.0.5a2?

### ISSUE THREAD

**Issue by agrier-lodo** [LooseLab/readfish#93]
It doesn't look like the `AccumulatingReadCache` class from read_until_client.py is utilized anywhere, and based on experimental data I'm not convinced read chunks are accumulating properly.  Is this feature working correctly in this version, as far as you know?

Very exciting technology, by the way.  Thank you.

**Comment by mattloose** [comment]
This is pre-release code aimed at getting our minknow 4 compatability up and running - because of additional issues we have recommended people use this for now. The full AccumulatingReadCache will be in our final 'stable' version utilsing the code base in Nanopores read until api which is itself derived from our original cache.

So - in this version, the accumulating cache is not doing anything. We will shortly (by the end of this week we hope) push a bug release update to address this and other questions.

Thanks
