### ISSUE TITLE
Bulk playback in minion-nc 20.06.5

### ISSUE THREAD

**Issue by TomHarrop** [LooseLab/readfish#98]
I'm struggling with FAST5 playback as described in the README with MinKNOW 20.06.5. I get  zero pores and no reads (like #65). However, I'm trying to replay the bulk fast5 linked in the README.

Of course this isn't a readfish problem, but I can't get the documented method to work so I thought I'd ask about it.

I checked that the full path to the bulk fast5 is in `sequencing_MIN106_DNA.toml` file and I reloaded the scripts in the "Start" screen. Everything looks like a normal sequencing run. I get the mux message but there are no pores, and no reads once sequencing starts.

I'm using `minion-nc=20.06.5-1~bionic` from the ONT repo, `nanoporetech/read_until_api@v3.0.0` from github (installed via `pip`) and `readfish==0.0.5a1` (also `pip`).

The MD5 sum of the fast5 I downloaded is

```
235aba65751726227a3e9a31adc0137c  PLSP57501_20170308_FNFAF14035_MN16458_sequencing_run_NOTT_Hum_wh1rs2_60428.fast5

```

I've tried ubuntu 18.04 and ubuntu 20.04, python 3.6, 3.7 and 3.8. (The ubuntu 20.04 / python3.8 setup didn't let me install ont-guppy from their repo.)

Thanks for this amazing work, it's going to be so useful once I have it up and running.

**Comment by mattloose** [comment]
Hi

Sorry for being slow responding to you? Have you resolved this? I would recommend checking the log files for Minknow - /var/logs/Minknow - and checking for errors associated with the playback runs. Also double check the messages that Minknow gives in the gui interface to see if there is anything extra there.

**Comment by TomHarrop** [comment]
Hi Matt,

I did get it working but I can't work out what causes it.

The "reload scripts" function seems to be the problem for me - it's like MinKNOW caches the scripts in `/opt/ont/minknow/conf/package/sequencing` at startup and the reload button doesn't do anything.

The way I solved it was deleting everything from `/var` and rebooting the computer, then replacing the TOML file **before** launching MinKNOW.

I did try exiting MinKNOW, clearing the contents of `/var` and restarting MinKNOW (without rebooting) but I was still getting the non-simulation TOML file. I see MinKNOW writes something to `/tmp`, I tried deleting that too but it didn't help.

Anyway it's working so you can close the issue, but I wanted to record what worked for me.

Thanks again!

**Comment by mattloose** [comment]
How do you reload the scripts?

This does work on all platforms we have tried so I wonder what you are doing?

**Comment by TomHarrop** [comment]
Sorry about this, now I think it was user error.

I'm running readfish and MinKNOW in a Singularity container. Seems to be something to do with the temporary filesystem - reloading scripts works as expected if I use a [persistent overlay](https://sylabs.io/guides/3.6/user-guide/persistent_overlays.html#file-system-image-overlay).

Thanks for your help.

**Comment by daniloimparato** [comment]
Hi @mattloose & team! I hope it is OK to use this issue to ask something about simulated runs.

I have been having a hard time replicating the read length histogram from the README (and also the updated one in [this PR](https://github.com/LooseLab/readfish/blob/1313c51848705c8982a321323049a56272d83229/README.md)).

Can you confirm if histograms are supposed to be exactly the same in different simulated runs? I'm using the bulk file you made available. It seems plausible that the simulation incorporates some nondeterministic behavior but I figured it would be better to ask you.

One of our simulated runs about 10 minutes in:
![image](https://user-images.githubusercontent.com/13784115/99288933-11a22880-281b-11eb-9634-34af074ab7c7.png)

**Comment by mattloose** [comment]
Hi - good to ask...

Have a look here: https://github.com/LooseLab/readfish/wiki/Basecalling-Settings

There may be some tweaks to basecalling that you can make - in particular the adapter settings - this is a change from MinKNOW 3.6 to 4.0 as we have now.

Hope this helps,

Matt

**Comment by daniloimparato** [comment]
Hey @mattloose, thanks for the quick response!

Valuable info on the wiki. Definitely should have checked it beforehand.

However, my colleagues and I haven't reached the selective sequencing step yet. We're still experimenting with the playback and the unblock-all response.

Let me break the question down a little further after reading the wiki and giving it some thought.

1. We couldn't approximate the [first read length histogram in the README](https://raw.githubusercontent.com/LooseLab/readfish/1313c51848705c8982a321323049a56272d83229/examples/images/15minuteControl.png) after 15 minutes as you described. However, we did manage to approximate it after letting it run for around 30 minutes. **Does this mean our basecalling is not keeping up with the signal as fast as it should?** The basecalled % mostly stays above 90%, running on a GTX 1080 Ti.

2. It seemed to me that the unblock-all response shouldn't be affected by anything basecalling-related, since no basecalling is needed to immediately unblock pores. Can you confirm this assumption?

3. Just out of curiosity, why don't reads in a playback run begin with an adapter sequence like in a live run? What would be the gain of deactivating the adapter detection for speed in a playback run if it is supposed to be activated during live runs anyway?

Please forgive me if this is not the appropriate place to ask these!

**Comment by mattloose** [comment]
Ah. Are you just running unblock all at the moment? If so - I’ve possibly misunderstood. 

In the unblock all script we are not basecalling. So. Not reaching similar performance as us after 15 minutes is indicative of overall computer performance and not basecalling. What CPU are you using?

This also confirms your assumption in 2. 

The answer to 3 is based on how the playback script works and what it does in response to an unblock. If you unblock a real run the molecule leaves the pore and is replaced by another complete with adapter. If you are running playback then the signal playing back is simply divided into a new read. That read starts with whatever signal was in that pore at that time in the original run and so is unlikely to be an adapter sequence as these are only found at the start of the read. 

I hope that helps!

**Comment by daniloimparato** [comment]
That does help a lot. Thanks!

We're running on an i7-7800X.
